### ISSUE TITLE
Use STS to handle overlapping roles?

### ISSUE THREAD

**Issue by slbmeh** [poise/citadel#19] opened 2015-06-22 06:05 UTC
Because of the single role limitation of instance profiles mentioned in #3 I tend to have restricted roles that have the ability to assume the privileged roles with STS.

Providing assume role capabilities may be a convenient way to write recipes requiring overlapping permissions between roles.  However, it still doesn't solve the complexities of configuring the roles for creating the instance profile role.

**Comment by coderanger** [comment] 2015-06-22 06:10
Yeah, this would basically result in every server needing its own IAM role, and if you have the tooling to do that you can just build the permissions in at that layer. Basically if you have enough tooling to build something around STS/AssumeRole then you could just use that directly with IAM so catch 22.

**Comment by slbmeh** [comment] 2015-06-22 06:17
There is still some convenience in wildcarding with paths for overlapping roles.

**Comment by coderanger** [comment] 2015-06-22 16:46
The problem is that every unique combination of roles that can you can assume needs to be a different role itself, which is exactly the reason to use the AssumeRole setup in the first place. If you assume that those roles will be generated by a script, and given the number you would need I think that's a safe assumption, you are back to having no benefit.

**Comment by coderanger** [comment] 2016-05-18 08:26
Closing this out.

**Closed by coderanger** 2016-05-18 08:26 UTC
